export const classScheduleMeta = {
  className: "4반",
  room: "205호",
  startDate: "2026-07-14",
  endDate: "2026-12-11",
  totalWeeks: 22,
};

export const classSchedule = [
  {
    date: "2026-07-14",
    day: "화",
    week: 1,
    course: "팀빌딩(심요한), Git 이해/활용 (5h)",
    instructor: "엄진영",
    kind: "course",
  },
  {
    date: "2026-07-15",
    day: "수",
    week: 1,
    course: "HTML, CSS, JavaScript",
    instructor: "엄진영",
    kind: "course",
  },
  {
    date: "2026-07-16",
    day: "목",
    week: 1,
    course: "HTML, CSS, JavaScript",
    instructor: "엄진영",
    kind: "course",
  },
  {
    date: "2026-07-17",
    day: "금",
    week: 1,
    course: "대체휴일(개천절)",
    instructor: "",
    kind: "holiday",
  },
  {
    date: "2026-07-20",
    day: "월",
    week: 2,
    course: "데이터 분석을 위한 Python 이해",
    instructor: "류홍걸",
    kind: "course",
  },
  {
    date: "2026-07-21",
    day: "화",
    week: 2,
    course: "데이터 분석을 위한 Python 이해",
    instructor: "류홍걸",
    kind: "course",
  },
  {
    date: "2026-07-22",
    day: "수",
    week: 2,
    course: "스마트 데이터 이해 및 활용",
    instructor: "류홍걸",
    kind: "course",
  },
  {
    date: "2026-07-23",
    day: "목",
    week: 2,
    course: "스마트 데이터 이해 및 활용",
    instructor: "류홍걸",
    kind: "course",
  },
  {
    date: "2026-07-24",
    day: "금",
    week: 2,
    course: "스마트 데이터 이해 및 활용",
    instructor: "류홍걸",
    kind: "course",
  },
  {
    date: "2026-07-27",
    day: "월",
    week: 3,
    course: "데이터 분석 개요 및 기초통계",
    instructor: "박병선",
    kind: "course",
  },
  {
    date: "2026-07-28",
    day: "화",
    week: 3,
    course: "데이터 분석 개요 및 기초통계",
    instructor: "박병선",
    kind: "course",
  },
  {
    date: "2026-07-29",
    day: "수",
    week: 3,
    course: "Prompt 설계와 Context",
    instructor: "한성훈",
    kind: "course",
  },
  {
    date: "2026-07-30",
    day: "목",
    week: 3,
    course: "LLM과 Transformer 아키텍처",
    instructor: "한성훈",
    kind: "course",
  },
  {
    date: "2026-07-31",
    day: "금",
    week: 3,
    course: "LLM과 Transformer 아키텍처",
    instructor: "한성훈",
    kind: "course",
  },
  {
    date: "2026-08-03",
    day: "월",
    week: 4,
    course: "Java, SpringBoot, Rest API 구현",
    instructor: "류홍걸",
    kind: "course",
  },
  {
    date: "2026-08-04",
    day: "화",
    week: 4,
    course: "Java, SpringBoot, Rest API 구현",
    instructor: "류홍걸",
    kind: "course",
  },
  {
    date: "2026-08-05",
    day: "수",
    week: 4,
    course: "Java, SpringBoot, Rest API 구현",
    instructor: "류홍걸",
    kind: "course",
  },
  {
    date: "2026-08-06",
    day: "목",
    week: 4,
    course: "Java, SpringBoot, Rest API 구현",
    instructor: "류홍걸",
    kind: "course",
  },
  {
    date: "2026-08-07",
    day: "금",
    week: 4,
    course: "Java, SpringBoot, Rest API 구현",
    instructor: "류홍걸",
    kind: "course",
  },
  {
    date: "2026-08-10",
    day: "월",
    week: 5,
    course: "Agile 방법론 및 MSA 개발",
    instructor: "류홍걸",
    kind: "course",
  },
  {
    date: "2026-08-11",
    day: "화",
    week: 5,
    course: "Agile 방법론 및 MSA 개발",
    instructor: "류홍걸",
    kind: "course",
  },
  {
    date: "2026-08-12",
    day: "수",
    week: 5,
    course: "sLLM 구현 및 Fine Tunning",
    instructor: "임성열",
    kind: "course",
  },
  {
    date: "2026-08-13",
    day: "목",
    week: 5,
    course: "sLLM 구현 및 Fine Tunning",
    instructor: "임성열",
    kind: "course",
  },
  {
    date: "2026-08-14",
    day: "금",
    week: 5,
    course: "실전 Feature Engineering",
    instructor: "이은호",
    kind: "course",
  },
  {
    date: "2026-08-17",
    day: "월",
    week: 6,
    course: "대체휴일 (광복절)",
    instructor: "",
    kind: "holiday",
  },
  {
    date: "2026-08-18",
    day: "화",
    week: 6,
    course: "Front-framework: Vue.js",
    instructor: "김일한",
    kind: "course",
  },
  {
    date: "2026-08-19",
    day: "수",
    week: 6,
    course: "Front-framework: Vue.js",
    instructor: "김일한",
    kind: "course",
  },
  {
    date: "2026-08-20",
    day: "목",
    week: 6,
    course: "Front-framework: Vue.js",
    instructor: "김일한",
    kind: "course",
  },
  {
    date: "2026-08-21",
    day: "금",
    week: 6,
    course: "Front-framework: Vue.js",
    instructor: "김일한",
    kind: "course",
  },
  {
    date: "2026-08-24",
    day: "월",
    week: 7,
    course: "컨테이너 이해 및 애플리케이션 컨테이너화",
    instructor: "신인철",
    kind: "course",
  },
  {
    date: "2026-08-25",
    day: "화",
    week: 7,
    course: "컨테이너 이해 및 애플리케이션 컨테이너화",
    instructor: "신인철",
    kind: "course",
  },
  {
    date: "2026-08-26",
    day: "수",
    week: 7,
    course: "쿠버네티스 이해 및 애플리케이션 배포",
    instructor: "신인철",
    kind: "course",
  },
  {
    date: "2026-08-27",
    day: "목",
    week: 7,
    course: "쿠버네티스 이해 및 애플리케이션 배포",
    instructor: "신인철",
    kind: "course",
  },
  {
    date: "2026-08-28",
    day: "금",
    week: 7,
    course: "특강(취업특강)",
    instructor: "",
    kind: "special",
  },
  {
    date: "2026-08-29",
    day: "토",
    week: 7,
    course: "특강(취업특강), 12시 종료(8시~12시, 식당O)",
    instructor: "",
    kind: "special",
  },
  {
    date: "2026-08-31",
    day: "월",
    week: 8,
    course: "Spring AI",
    instructor: "정윤석",
    kind: "course",
  },
  {
    date: "2026-09-01",
    day: "화",
    week: 8,
    course: "Spring AI",
    instructor: "정윤석",
    kind: "course",
  },
  {
    date: "2026-09-02",
    day: "수",
    week: 8,
    course: "웹 서비스 개발 mini-Project",
    instructor: "윤재성",
    kind: "project",
  },
  {
    date: "2026-09-03",
    day: "목",
    week: 8,
    course: "웹 서비스 개발 mini-Project",
    instructor: "윤재성",
    kind: "project",
  },
  {
    date: "2026-09-04",
    day: "금",
    week: 8,
    course: "웹 서비스 개발 mini-Project",
    instructor: "윤재성",
    kind: "project",
  },
  {
    date: "2026-09-07",
    day: "월",
    week: 9,
    course: "머신러닝 및 딥러닝 이해",
    instructor: "김준범",
    kind: "course",
  },
  {
    date: "2026-09-08",
    day: "화",
    week: 9,
    course: "머신러닝 및 딥러닝 이해",
    instructor: "김준범",
    kind: "course",
  },
  {
    date: "2026-09-09",
    day: "수",
    week: 9,
    course: "머신러닝 및 딥러닝 이해",
    instructor: "김준범",
    kind: "course",
  },
  {
    date: "2026-09-10",
    day: "목",
    week: 9,
    course: "모델 개발 및 최적화",
    instructor: "김준범",
    kind: "course",
  },
  {
    date: "2026-09-11",
    day: "금",
    week: 9,
    course: "모델 개발 및 최적화",
    instructor: "김준범",
    kind: "course",
  },
  {
    date: "2026-09-14",
    day: "월",
    week: 10,
    course: "쿠버네티스 실무 심화",
    instructor: "박보경",
    kind: "course",
  },
  {
    date: "2026-09-15",
    day: "화",
    week: 10,
    course: "쿠버네티스 실무 심화",
    instructor: "박보경",
    kind: "course",
  },
  {
    date: "2026-09-16",
    day: "수",
    week: 10,
    course: "쿠버네티스 실무 심화",
    instructor: "박보경",
    kind: "course",
  },
  {
    date: "2026-09-17",
    day: "목",
    week: 10,
    course: "특강 (도메인특강, 프로젝트 현장 사례)",
    instructor: "",
    kind: "special",
  },
  {
    date: "2026-09-18",
    day: "금",
    week: 10,
    course: "생성형 AI 서비스 개발의 이해/활용 (LangChain)",
    instructor: "김경난",
    kind: "course",
  },
  {
    date: "2026-09-21",
    day: "월",
    week: 11,
    course: "생성형 AI 서비스 개발의 이해/활용 (LangChain)",
    instructor: "김경난",
    kind: "course",
  },
  {
    date: "2026-09-22",
    day: "화",
    week: 11,
    course: "생성형 AI 서비스 개발의 이해/활용 (LangChain)",
    instructor: "김경난",
    kind: "course",
  },
  {
    date: "2026-09-23",
    day: "수",
    week: 11,
    course: "자체휴강",
    instructor: "",
    kind: "holiday",
  },
  {
    date: "2026-09-24",
    day: "목",
    week: 11,
    course: "추석연휴",
    instructor: "",
    kind: "holiday",
  },
  {
    date: "2026-09-25",
    day: "금",
    week: 11,
    course: "추석연휴",
    instructor: "",
    kind: "holiday",
  },
  {
    date: "2026-09-26",
    day: "토",
    week: 11,
    course: "추석연휴",
    instructor: "",
    kind: "holiday",
  },
  {
    date: "2026-09-27",
    day: "일",
    week: 11,
    course: "추석연휴",
    instructor: "",
    kind: "holiday",
  },
  {
    date: "2026-09-28",
    day: "월",
    week: 12,
    course: "RAG Pipeline 설계 및 구축",
    instructor: "김경난",
    kind: "course",
  },
  {
    date: "2026-09-29",
    day: "화",
    week: 12,
    course: "RAG Pipeline 설계 및 구축",
    instructor: "김경난",
    kind: "course",
  },
  {
    date: "2026-09-30",
    day: "수",
    week: 12,
    course: "RAG Pipeline 설계 및 구축",
    instructor: "김경난",
    kind: "course",
  },
  {
    date: "2026-10-01",
    day: "목",
    week: 12,
    course: "데이터 분석 mini-Project",
    instructor: "박보경",
    kind: "project",
  },
  {
    date: "2026-10-02",
    day: "금",
    week: 12,
    course: "데이터 분석 mini-Project",
    instructor: "박보경",
    kind: "project",
  },
  {
    date: "2026-10-05",
    day: "월",
    week: 13,
    course: "대체휴일(개천절)",
    instructor: "",
    kind: "holiday",
  },
  {
    date: "2026-10-06",
    day: "화",
    week: 13,
    course: "모델 서빙 및 AIOps 구성",
    instructor: "임성열",
    kind: "course",
  },
  {
    date: "2026-10-07",
    day: "수",
    week: 13,
    course: "모델 서빙 및 AIOps 구성",
    instructor: "임성열",
    kind: "course",
  },
  {
    date: "2026-10-08",
    day: "목",
    week: 13,
    course: "모델 서빙 및 AIOps 구성",
    instructor: "임성열",
    kind: "course",
  },
  {
    date: "2026-10-09",
    day: "금",
    week: 13,
    course: "한글날",
    instructor: "",
    kind: "holiday",
  },
  {
    date: "2026-10-12",
    day: "월",
    week: 14,
    course: "AI Agent 설계 및 구축",
    instructor: "김경난",
    kind: "course",
  },
  {
    date: "2026-10-13",
    day: "화",
    week: 14,
    course: "AI Agent 설계 및 구축",
    instructor: "김경난",
    kind: "course",
  },
  {
    date: "2026-10-14",
    day: "수",
    week: 14,
    course: "Vector DB",
    instructor: "김경난",
    kind: "course",
  },
  {
    date: "2026-10-15",
    day: "목",
    week: 14,
    course: "AI Agent Capstone",
    instructor: "김경난",
    kind: "project",
  },
  {
    date: "2026-10-16",
    day: "금",
    week: 14,
    course: "AI Agent Capstone",
    instructor: "김경난",
    kind: "project",
  },
  {
    date: "2026-10-19",
    day: "월",
    week: 15,
    course: "AI Agent Capstone",
    instructor: "김경난",
    kind: "project",
  },
  {
    date: "2026-10-20",
    day: "화",
    week: 15,
    course: "AI 서비스 개발 Mini-project",
    instructor: "김경난",
    kind: "project",
  },
  {
    date: "2026-10-21",
    day: "수",
    week: 15,
    course: "AI 서비스 개발 Mini-project",
    instructor: "김경난",
    kind: "project",
  },
  {
    date: "2026-10-22",
    day: "목",
    week: 15,
    course: "AI 서비스 개발 Mini-project",
    instructor: "김경난",
    kind: "project",
  },
  {
    date: "2026-10-23",
    day: "금",
    week: 15,
    course: "DevOps 이해 및 활용",
    instructor: "김경난",
    kind: "course",
  },
  {
    date: "2026-10-26",
    day: "월",
    week: 16,
    course: "DevOps 이해 및 활용",
    instructor: "김경난",
    kind: "course",
  },
  {
    date: "2026-10-27",
    day: "화",
    week: 16,
    course: "AI 프로젝트 방법론",
    instructor: "",
    kind: "project",
  },
  {
    date: "2026-10-28",
    day: "수",
    week: 16,
    course: "팀프로젝트",
    instructor: "백정열",
    kind: "project",
  },
  {
    date: "2026-10-29",
    day: "목",
    week: 16,
    course: "팀프로젝트",
    instructor: "박병선",
    kind: "project",
  },
  {
    date: "2026-10-30",
    day: "금",
    week: 16,
    course: "팀프로젝트",
    instructor: "박병선",
    kind: "project",
  },
  {
    date: "2026-11-02",
    day: "월",
    week: 17,
    course: "팀프로젝트",
    instructor: "이용우",
    kind: "project",
  },
  {
    date: "2026-11-03",
    day: "화",
    week: 17,
    course: "팀프로젝트",
    instructor: "이용우",
    kind: "project",
  },
  {
    date: "2026-11-04",
    day: "수",
    week: 17,
    course: "팀프로젝트",
    instructor: "이용우",
    kind: "project",
  },
  {
    date: "2026-11-05",
    day: "목",
    week: 17,
    course: "팀프로젝트",
    instructor: "박창렴",
    kind: "project",
  },
  {
    date: "2026-11-06",
    day: "금",
    week: 17,
    course: "팀프로젝트",
    instructor: "박창렴",
    kind: "project",
  },
  {
    date: "2026-11-09",
    day: "월",
    week: 18,
    course: "팀프로젝트",
    instructor: "류홍걸",
    kind: "project",
  },
  {
    date: "2026-11-10",
    day: "화",
    week: 18,
    course: "팀프로젝트",
    instructor: "류홍걸",
    kind: "project",
  },
  {
    date: "2026-11-11",
    day: "수",
    week: 18,
    course: "팀프로젝트",
    instructor: "임성열",
    kind: "project",
  },
  {
    date: "2026-11-12",
    day: "목",
    week: 18,
    course: "팀프로젝트 (중간점검)",
    instructor: "임성열",
    kind: "project",
  },
  {
    date: "2026-11-13",
    day: "금",
    week: 18,
    course: "팀프로젝트",
    instructor: "임성열",
    kind: "project",
  },
  {
    date: "2026-11-16",
    day: "월",
    week: 19,
    course: "팀프로젝트",
    instructor: "강병호",
    kind: "project",
  },
  {
    date: "2026-11-17",
    day: "화",
    week: 19,
    course: "팀프로젝트",
    instructor: "강병호",
    kind: "project",
  },
  {
    date: "2026-11-18",
    day: "수",
    week: 19,
    course: "팀프로젝트",
    instructor: "강병호",
    kind: "project",
  },
  {
    date: "2026-11-19",
    day: "목",
    week: 19,
    course: "팀프로젝트",
    instructor: "강병호",
    kind: "project",
  },
  {
    date: "2026-11-20",
    day: "금",
    week: 19,
    course: "팀프로젝트",
    instructor: "강병호",
    kind: "project",
  },
  {
    date: "2026-11-23",
    day: "월",
    week: 20,
    course: "팀프로젝트",
    instructor: "이현민",
    kind: "project",
  },
  {
    date: "2026-11-24",
    day: "화",
    week: 20,
    course: "팀프로젝트",
    instructor: "이현민",
    kind: "project",
  },
  {
    date: "2026-11-25",
    day: "수",
    week: 20,
    course: "팀프로젝트",
    instructor: "임성열",
    kind: "project",
  },
  {
    date: "2026-11-26",
    day: "목",
    week: 20,
    course: "팀프로젝트",
    instructor: "임성열",
    kind: "project",
  },
  {
    date: "2026-11-27",
    day: "금",
    week: 20,
    course: "팀프로젝트",
    instructor: "임성열",
    kind: "project",
  },
  {
    date: "2026-11-30",
    day: "월",
    week: 21,
    course: "팀프로젝트",
    instructor: "강병호",
    kind: "project",
  },
  {
    date: "2026-12-01",
    day: "화",
    week: 21,
    course: "팀프로젝트",
    instructor: "강병호",
    kind: "project",
  },
  {
    date: "2026-12-02",
    day: "수",
    week: 21,
    course: "팀프로젝트",
    instructor: "강병호",
    kind: "project",
  },
  {
    date: "2026-12-03",
    day: "목",
    week: 21,
    course: "팀프로젝트",
    instructor: "강병호",
    kind: "project",
  },
  {
    date: "2026-12-04",
    day: "금",
    week: 21,
    course: "팀프로젝트",
    instructor: "강병호",
    kind: "project",
  },
  {
    date: "2026-12-07",
    day: "월",
    week: 22,
    course: "팀프로젝트",
    instructor: "류홍걸",
    kind: "project",
  },
  {
    date: "2026-12-08",
    day: "화",
    week: 22,
    course: "팀프로젝트",
    instructor: "류홍걸",
    kind: "project",
  },
  {
    date: "2026-12-09",
    day: "수",
    week: 22,
    course: "팀프로젝트",
    instructor: "류홍걸",
    kind: "project",
  },
  {
    date: "2026-12-10",
    day: "목",
    week: 22,
    course: "최종평가(예선)",
    instructor: "류홍걸",
    kind: "evaluation",
  },
  {
    date: "2026-12-11",
    day: "금",
    week: 22,
    course: "최종평가(본선) / 수료식 (16시 종료)",
    instructor: "류홍걸",
    kind: "evaluation",
  },
];
